/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: ca224f319e55d730819f436507a898e6)
interface __BaseEnv_Env {
	EMAIL: SendEmail;
	IP_RATE_LIMITER: RateLimit;
	EMAIL_RATE_LIMITER: RateLimit;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
